### ISSUE TITLE
TODO: Metrics-related Notes that need to find a home

### ISSUE THREAD

**Issue by SMotaal** [chaoss/metrics#173]
# TODO

Please help find a home for each of the following:

- Appeared in [Event Diversity - Attendees Demographics](https://docs.google.com/document/d/1psK_UH5uLeiVHagpoJbCtm8dF1nIshfCx6qXXJWe4yc/edit):

  - [ ] if you ask before and after the event or collect data at different points in time, the data may not be able to work together. For example, asking for perception and “objective” numbers should stay together.

  - [ ] Stipulative terminology section in surveys can help with consistent answers across respondents. [Survey best practices]

  - [ ] Note about survey design: We can use the emoji-scale:  ◯ 😔 ◯ 😟 ◯ 😐 ◯ 😊 ◯ 🤩

---

Please feel free do add/check items as needed!

**Comment by GeorgLink** [comment]
These are general "best practices" that we should capture outside of the individual metrics. Maybe start a "best practices for survey design" document somewhere.

**Comment by GeorgLink** [comment]
@Nebrethar shared the following information related to using a emoji-scale

* https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0144296 
* http://kt.ijs.si/data/Emoji_sentiment_ranking/

**Comment by SMotaal** [comment]
Some links are funny in Chrome maybe others (this might work better?):

- [https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0144296 ](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0144296 )

**Comment by germonprez** [comment]
that works (copy and paste)
