### ISSUE TITLE
Idea: Metric quality checklist

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/metrics#193]
The latest addition to the template, like #192, #191 , and #189 are all requirements or suggestions.

Idea: Pull together all requirements in a checklist that we go through before releasing a metric, including content quality checks and technical requirement checks.

This could be an issue template that WGs use for new/updated metrics and look like:

---

# CHAOSS Metric Quality Checklist

## Content Quality
- [ ] Required headings are filled in, including Question.
- [ ] Description provides context to metric
- [ ] Objectives list sample uses for the metric and desired outcomes
- [ ] If any, DEI uses of the metric are included Objectives
- [ ] ...

## Technical Requirements
- [ ] Metric file follows naming convention
- [ ] Images are included using markdown and relative links
- [ ] Focus area entry created and links to the metric
- [ ] ...

## Process Requirements
- [ ] Release issue for comments during review period
- [ ] Entry to release notes 
- [ ] New/updated metric announced on mailing list
- [ ] Issue was created to kick-off translation to other languages
- [ ] ...

**Comment by lucasgonze** [comment]
Lucas and Vinod to create issue template.

**Comment by vinodkahuja** [comment]
I have created a Google Doc for refining the checklist and copied the above-mentioned points in it. I will keep on adding stuff to it in a day or two. 
https://docs.google.com/document/d/1FJQm2HLXfwYH7VD4zjzjWkoMP1RQg63FPe-tC061jC8/edit?usp=sharing

**Comment by GeorgLink** [comment]
Thanks @vinodkahuja -- I edited and refactored the checklist. Please review and revise again so that it is understandable and sensible for a WG maintainer

**Comment by vinodkahuja** [comment]
Thanks @GeorgLink I have made few minor changes and added link to the metric template. Rest looks good to me. @klumb @lucasgonze please review. if it looks good then we can release it.

**Comment by GeorgLink** [comment]
Thanks @vinodkahuja

**Comment by GeorgLink** [comment]
Feedback from @lucasgonze on today's monthly call:

- the list is too long: reduce or split up

We discussed that we could turn this into two issue templates:

1. Add Metric to Repo (Quality + Technical Requirements)
1. Get feedback and prepare release (Process)

**Comment by lucasgonze** [comment]
I reorganized the Google Doc to reflect Georg's comment.

**Comment by klumb** [comment]
Hi @lucasgonze I just got back from traveling and added my edits to the google doc

Sorry about the delay in editing it. 

https://docs.google.com/document/d/1FJQm2HLXfwYH7VD4zjzjWkoMP1RQg63FPe-tC061jC8/edit#heading=h.uja3g8utxhdw

**Comment by GeorgLink** [comment]
Kevin,

Thanks for your extensive review and edits on the process.

Best,
Georg
